import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { DeleteGearButton, EditGearLink, OrderStatusAction } from "@/components/provider/provider-actions";
import { GearForm } from "@/components/provider/gear-form";
import { StatusBadge } from "@/components/shared/status-badge";
import { DashboardPanel, EmptyState, ErrorState, PageContainer } from "@/components/ui/gearup";
import { Button } from "@/components/ui/button";
import { getGearById } from "@/service/gear/gearService";
import { getProviderDashboardData, getProviderFormOptions, gearForOrder } from "@/service/provider/providerDashboardService";
import { getMe } from "@/service/auth/getMe";
import type { Gear } from "@/types/gear";
import type { Rental } from "@/types/rental";
import { CalendarDays, PackageOpen } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

function currency(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value); }
function date(value: string) { const parsed = new Date(`${value.slice(0, 10)}T12:00:00`); return Number.isNaN(parsed.getTime()) ? "Date unavailable" : new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(parsed); }
function gearTitle(gear: Gear | undefined, order: Rental) { return gear?.name ?? `Gear #${order.gearId}`; }

async function loadProviderData() { try { return await getProviderDashboardData(); } catch { return null; } }
function ProviderError() { return <PageContainer className="py-12"><ErrorState title="We could not load provider data" description="Please try again shortly." /></PageContainer>; }
function Shell({ title, children }: { title: string; children: React.ReactNode }) { return <DashboardShell role="Provider"><PageContainer><span className="sr-only">{title}</span>{children}</PageContainer></DashboardShell>; }
function Heading({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="gearup-h1">{title}</h1><p className="gearup-body mt-1.5">{description}</p></div>{action}</div>; }

export async function ProviderDashboardView() {
  const data = await loadProviderData(); if (!data) return <ProviderError />;
  const stats = [{ label: "Total gear listed", value: data.gear.length }, { label: "Active rentals", value: data.orders.filter((order) => ["PAID", "PICKED_UP"].includes(order.status)).length }, { label: "Pending orders", value: data.orders.filter((order) => order.status === "PLACED").length }, { label: "Available gear", value: data.gear.filter((gear) => gear.available && gear.stock > 0).length }];
  return <Shell title="Provider dashboard"><Heading title="Provider dashboard" description="Overview of your listings and incoming rentals." action={<Button asChild><Link href="/dashboard/provider/gear/new">Add new gear</Link></Button>} /><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <div className="gearup-card p-5" key={stat.label}><p className="text-[13px] font-semibold text-muted-foreground">{stat.label}</p><p className="mt-2 text-[26px] font-extrabold">{stat.value}</p></div>)}</div><div className="mt-8 grid items-start gap-6 xl:grid-cols-2"><DashboardPanel title="Recent orders" action={<Button variant="link" size="sm" asChild><Link href="/dashboard/provider/orders">View all</Link></Button>}><ProviderOrderTable orders={data.orders.slice(0, 5)} gear={data.gear} /></DashboardPanel><DashboardPanel title="Inventory overview" action={<Button variant="link" size="sm" asChild><Link href="/dashboard/provider/gear">Manage</Link></Button>}>{data.gear.length ? <div className="space-y-2">{data.gear.slice(0, 5).map((gear) => <div className="flex items-center gap-3 border-b border-border py-2.5 last:border-0" key={gear.id}><div className="flex size-10 items-center justify-center rounded-md bg-secondary text-primary"><PackageOpen className="size-5" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{gear.name}</p><p className="gearup-caption">{gear.stock} in stock</p></div><StatusBadge status={gear.available && gear.stock > 0 ? "PICKED_UP" : "CANCELLED"} /></div>)}</div> : <EmptyState title="No gear listed" description="Add your first listing to start receiving rentals." action={<Button size="sm" asChild><Link href="/dashboard/provider/gear/new">Add gear</Link></Button>} />}</DashboardPanel></div></Shell>;
}

export async function ProviderInventoryView() { const data = await loadProviderData(); if (!data) return <ProviderError />; return <Shell title="Inventory"><Heading title="My gear" description="Manage the equipment you list on GearUp." action={<Button asChild><Link href="/dashboard/provider/gear/new">Add gear</Link></Button>} /><DashboardPanel className="mt-7">{data.gear.length ? <div className="overflow-x-auto"><table className="gearup-table"><thead><tr><th>Gear</th><th>Category</th><th>Price/day</th><th>Stock</th><th>Availability</th><th>Actions</th></tr></thead><tbody>{data.gear.map((gear) => <tr key={gear.id}><td className="font-semibold">{gear.name}</td><td>{gear.category}</td><td>{currency(gear.pricePerDay)}</td><td>{gear.stock}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${gear.available && gear.stock > 0 ? "bg-[#dcfce7] text-[#166534]" : "bg-[#fee2e2] text-[#991b1b]"}`}>{gear.available && gear.stock > 0 ? "Available" : "Unavailable"}</span></td><td><div className="flex gap-2"><EditGearLink id={gear.id} /><DeleteGearButton gear={gear} /></div></td></tr>)}</tbody></table></div> : <EmptyState title="No gear listed" description="Add equipment to start building your provider inventory." action={<Button asChild><Link href="/dashboard/provider/gear/new">Add gear</Link></Button>} />}</DashboardPanel></Shell>; }

async function loadProviderGearEdit(id: string) { try { const response = await getGearById(id); if (!response.success || !response.data) return { kind: "missing" as const }; return { kind: "success" as const, gear: response.data }; } catch { return { kind: "error" as const }; } }

export async function ProviderGearFormView({ id }: { id?: string }) { const categories = await getProviderFormOptions(); if (!id) return <Shell title="Add gear"><Heading title="Add new gear" description="Create a listing for customers to rent." /><DashboardPanel className="mt-7"><GearForm categories={categories} /></DashboardPanel></Shell>; const result = await loadProviderGearEdit(id); if (result.kind === "missing") notFound(); if (result.kind === "error") return <ProviderError />; return <Shell title="Edit gear"><Heading title="Edit gear" description="Update your listing details and availability." /><DashboardPanel className="mt-7"><GearForm gear={result.gear} categories={categories} /></DashboardPanel></Shell>; }

export async function ProviderOrdersView() { const data = await loadProviderData(); if (!data) return <ProviderError />; return <Shell title="Orders"><Heading title="Incoming orders" description="Manage rentals for your provider inventory." /><DashboardPanel className="mt-7"><ProviderOrderTable orders={data.orders} gear={data.gear} /></DashboardPanel></Shell>; }

function ProviderOrderTable({ orders, gear }: { orders: Rental[]; gear: Gear[] }) { if (!orders.length) return <EmptyState title="No incoming orders" description="New rental requests for your gear will appear here." />; return <div className="overflow-x-auto"><table className="gearup-table"><thead><tr><th>Order</th><th>Customer</th><th>Gear</th><th>Dates</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td className="font-semibold">#{order.id}</td><td className="text-muted-foreground">Customer details unavailable</td><td>{gearTitle(gearForOrder(gear, order), order)}</td><td><span className="flex items-center gap-1 text-sm"><CalendarDays className="size-3.5 text-muted-foreground" />{date(order.startDate)} – {date(order.endDate)}</span></td><td className="font-semibold">{currency(order.totalAmount)}</td><td><StatusBadge status={order.status} /></td><td><OrderStatusAction order={order} /></td></tr>)}</tbody></table></div>; }

export async function ProviderProfileView() { const user = await getMe(); if (!user.success || !user.data?.profile) return <ProviderError />; const profile = user.data.profile; return <Shell title="Profile"><Heading title="Profile" description="Your provider account details." /><DashboardPanel className="mt-7 max-w-2xl"><div className="flex items-center gap-3 border-b border-border pb-5"><span className="flex size-14 items-center justify-center rounded-full bg-primary text-lg font-bold text-primary-foreground">{profile.name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase()}</span><div><h2 className="font-bold">{profile.name}</h2><p className="gearup-small">Provider account</p></div></div><div className="border-b border-border py-3 text-sm"><span className="text-muted-foreground">Name</span><p className="mt-1 font-semibold">{profile.name}</p></div><div className="border-b border-border py-3 text-sm"><span className="text-muted-foreground">Email</span><p className="mt-1 font-semibold">{profile.email}</p></div><div className="py-3 text-sm"><span className="text-muted-foreground">Account status</span><p className="mt-1 font-semibold">{profile.activeStatus}</p></div></DashboardPanel></Shell>; }
