import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { AdminUsers } from "@/components/admin/admin-users";
import { DashboardPanel, EmptyState, ErrorState, PageContainer } from "@/components/ui/gearup";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/shared/status-badge";
import { getMe } from "@/service/auth/getMe";
import { getAdminGear, getAdminOrders, getAdminUsers } from "@/service/admin/adminService";
import { CalendarDays } from "lucide-react";
import Link from "next/link";

function currency(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value); }
function date(value?: string) { if (!value) return "Date unavailable"; const parsed = new Date(`${value.slice(0, 10)}T12:00:00`); return Number.isNaN(parsed.getTime()) ? "Date unavailable" : new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(parsed); }
function roleLabel(role: string) { return role === "USER" ? "Customer" : role === "AUTHOR" ? "Provider" : role === "ADMIN" ? "Admin" : role; }
function Shell({ title, children }: { title: string; children: React.ReactNode }) { return <DashboardShell role="Admin"><PageContainer><span className="sr-only">{title}</span>{children}</PageContainer></DashboardShell>; }
function Heading({ title, description }: { title: string; description: string }) { return <div><h1 className="gearup-h1">{title}</h1><p className="gearup-body mt-1.5">{description}</p></div>; }
function Failure() { return <PageContainer className="py-12"><ErrorState title="We could not load admin data" description="Please try again shortly." /></PageContainer>; }

async function loadAdminData() { try { const [users, gear, orders] = await Promise.all([getAdminUsers(), getAdminGear(), getAdminOrders()]); if (!users.success || !gear.success || !orders.success) return null; return { users: users.data ?? [], gear: gear.data ?? [], orders: orders.data ?? [] }; } catch { return null; } }

export async function AdminDashboardView() { const data = await loadAdminData(); if (!data) return <Failure />; const stats = [{ label: "Total users", value: data.users.length }, { label: "Active gear", value: data.gear.filter((item) => item.available && item.stock > 0).length }, { label: "Total rentals", value: data.orders.length }, { label: "Suspended users", value: data.users.filter((user) => user.activeStatus === "Suspended").length }]; return <Shell title="Platform overview"><Heading title="Platform overview" description="GearUp-wide health and moderation status." /><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <div className="gearup-card p-5" key={stat.label}><p className="text-[13px] font-semibold text-muted-foreground">{stat.label}</p><p className="mt-2 text-[26px] font-extrabold">{stat.value}</p></div>)}</div><div className="mt-8 grid items-start gap-6 xl:grid-cols-2"><DashboardPanel title="Recently joined users" action={<Button variant="link" size="sm" asChild><Link href="/dashboard/admin/users">View all</Link></Button>}>{data.users.length ? <div className="space-y-2">{data.users.slice().sort((a, b) => (b.createdAt ?? "").localeCompare(a.createdAt ?? "")).slice(0, 5).map((user) => <div className="flex items-center gap-3 border-b border-border py-2.5 last:border-0" key={user.id}><span className="flex size-9 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">{user.name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{user.name}</p><p className="gearup-caption">{roleLabel(user.role)}</p></div><span className="text-xs text-muted-foreground">{user.activeStatus}</span></div>)}</div> : <EmptyState title="No users yet" description="Registered users will appear here." />}</DashboardPanel><DashboardPanel title="Platform signals"><div className="space-y-3 text-sm"><p className="flex items-center justify-between border-b border-border pb-3"><span className="text-muted-foreground">Gear listings</span><strong>{data.gear.length}</strong></p><p className="flex items-center justify-between border-b border-border pb-3"><span className="text-muted-foreground">Available listings</span><strong>{data.gear.filter((item) => item.available && item.stock > 0).length}</strong></p><p className="flex items-center justify-between"><span className="text-muted-foreground">Orders requiring review</span><strong>{data.orders.filter((order) => ["PLACED", "CANCELLED"].includes(order.status)).length}</strong></p></div></DashboardPanel></div></Shell>; }

export async function AdminUsersView() { const response = await getAdminUsers().catch(() => null); if (!response?.success) return <Failure />; return <Shell title="User management"><Heading title="User management" description="Search and moderate GearUp accounts." /><DashboardPanel className="mt-7"><AdminUsers users={response.data ?? []} /></DashboardPanel></Shell>; }

export async function AdminGearView() { const response = await getAdminGear().catch(() => null); if (!response?.success) return <Failure />; const gear = response.data ?? []; return <Shell title="Gear moderation"><Heading title="Gear moderation" description="Inspect listings across every provider on the platform." /><DashboardPanel className="mt-7">{gear.length ? <div className="overflow-x-auto"><table className="gearup-table"><thead><tr><th>Gear</th><th>Provider</th><th>Category</th><th>Price/day</th><th>Availability</th><th>Inspection</th></tr></thead><tbody>{gear.map((item) => <tr key={item.id}><td className="font-semibold">{item.name}</td><td>{item.provider?.name ?? "Provider unavailable"}</td><td>{item.category}</td><td>{currency(item.pricePerDay)}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.available && item.stock > 0 ? "bg-[#dcfce7] text-[#166534]" : "bg-[#fee2e2] text-[#991b1b]"}`}>{item.available && item.stock > 0 ? "Available" : "Unavailable"}</span></td><td><Button variant="outline" size="sm" asChild><Link href={`/gear/${item.id}`}>Inspect</Link></Button></td></tr>)}</tbody></table></div> : <EmptyState title="No gear listings" description="Provider listings will appear here for moderation." />}</DashboardPanel></Shell>; }

export async function AdminOrdersView() { const response = await getAdminOrders().catch(() => null); if (!response?.success) return <Failure />; const orders = response.data ?? []; return <Shell title="Order moderation"><Heading title="Order moderation" description="Every rental order placed across the platform." /><DashboardPanel className="mt-7">{orders.length ? <div className="overflow-x-auto"><table className="gearup-table"><thead><tr><th>Order</th><th>Customer</th><th>Gear</th><th>Provider</th><th>Dates</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td className="font-semibold">#{order.id}</td><td className="text-muted-foreground">Customer details unavailable</td><td>Gear #{order.gearId}</td><td className="text-muted-foreground">Provider details unavailable</td><td><span className="flex items-center gap-1 text-sm"><CalendarDays className="size-3.5 text-muted-foreground" />{date(order.startDate)} – {date(order.endDate)}</span></td><td className="font-semibold">{currency(order.totalAmount)}</td><td><StatusBadge status={order.status} /></td></tr>)}</tbody></table></div> : <EmptyState title="No orders yet" description="Rental orders will appear here for moderation." />}</DashboardPanel></Shell>; }

export async function AdminProfileView() { const user = await getMe(); if (!user.success || !user.data?.profile) return <Failure />; const profile = user.data.profile; return <Shell title="Profile"><Heading title="Profile" description="Your administrator account details." /><DashboardPanel className="mt-7 max-w-2xl"><div className="flex items-center gap-3 border-b border-border pb-5"><span className="flex size-14 items-center justify-center rounded-full bg-primary text-lg font-bold text-primary-foreground">{profile.name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase()}</span><div><h2 className="font-bold">{profile.name}</h2><p className="gearup-small">Administrator account</p></div></div><div className="border-b border-border py-3 text-sm"><span className="text-muted-foreground">Name</span><p className="mt-1 font-semibold">{profile.name}</p></div><div className="border-b border-border py-3 text-sm"><span className="text-muted-foreground">Email</span><p className="mt-1 font-semibold">{profile.email}</p></div><div className="py-3 text-sm"><span className="text-muted-foreground">Account status</span><p className="mt-1 font-semibold">{profile.activeStatus}</p></div></DashboardPanel></Shell>; }
